sudo: required

language: php

service: docker

before_install:
    - docker-compose up -d
    - docker-compose exec workspace composer install
    - cp .env.example .env
    - docker-compose exec workspace php artisan key:generate

script:
    - docker-compose exec workspace ./vendor/bin/phpunit 
