version: '2'

services:

    workspace:
        image: niisantokyo/laradock_ws
        volumes:
            - ./:/var/www/laravel
        tty: true

    mysql_test:
        image: mysql
        ports:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
